### ISSUE TITLE
Get-O365ModuleFile is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by alaurie** [Josverl/Connect-O365#4]
I am getting the below error when running Connect-O365.ps1 -Install. The ConnectO365 module has already been installed as per the Powershell gallery instructions.

Get-O365ModuleFile : The term 'Get-O365ModuleFile' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Program Files\WindowsPowerShell\Scripts\Connect-O365.ps1:609 char:9
-         Get-O365ModuleFile
-         ~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : ObjectNotFound: (Get-O365ModuleFile:String) [], CommandNotFoundException
  - FullyQualifiedErrorId : CommandNotFoundException

**Comment by Josverl** [comment]
Hi, thanks for the report. This should now be resolved with vwersion 0.8.2.2 of the supporting connecto365 module.
The underlying cause appear to be that on the RS1 flavor of powershell the cmdlet is treated as a function in the export module. 

It should be fixed by running update-module.

https://github.com/Josverl/Connect-O365/commit/0395e8fdad47e42b03ce81729e67a310ddf03cbb
